# -*- coding: utf-8 -*-
"""Set_Operations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R-GMQ2aNzv6GLcKWbuH1fHGenrBkqg7u
"""

#set operation
l1=eval(input("Enter the first set"))
l2=eval(input("Enter the second set"))
print(f'union of l1 and l2 is {l1|l2}')
print(f'intersection of l1 and l2 is {l1 & l2}')
print(f'difference of l1 and l2 is {l1-l2}')
print(f'symmetric difference of l1 and l2 is {(l1-l2)|(l2-l1)}')